language : python

before_script : 
  - virtual env testenv
  - source testenv/bin/activate
  - pip install -r requirement.txt

script :
  - cd tests
  - coverage run parsergift_test.py

after_success:
  - coveralls
